"""Add quantity, reorder_point, and date_added fields to grocery_items

Revision ID: 3d7f8a5e9c12
Revises: 2c40bdc99697
Create Date: 2025-11-18 03:17:00.000000

"""
from alembic import op
import sqlalchemy as sa
from datetime import date

# revision identifiers, used by Alembic.
revision = '3d7f8a5e9c12'
down_revision = '2c40bdc99697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns with default values
    op.add_column('grocery_items', sa.Column('quantity', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('grocery_items', sa.Column('reorder_point', sa.Integer(), nullable=False, server_default='10'))
    op.add_column('grocery_items', sa.Column('date_added', sa.Date(), nullable=False, server_default=sa.text('CURRENT_DATE')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grocery_items', 'date_added')
    op.drop_column('grocery_items', 'reorder_point')
    op.drop_column('grocery_items', 'quantity')
    # ### end Alembic commands ###
